name: MKS Robin E3D Firmware Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Build Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git build-essential

      - name: Configure and Build Klipper Firmware
        run: |
          git clone https://github.com/Klipper3d/klipper.git --depth=1
          cd klipper
          
          # MKS Robin E3D v1.1 için Klipper make menuconfig ayarları
          # Bu ayarlar LPC1768 işlemcisi ve bootloader için kritiktir.
          # Doğru derleyiciyi seçmesini sağlamak için gerekli tüm ayarları içerir.
          cat > .config << EOF
          CONFIG_MCU="lpc1768"
          CONFIG_LPC176X_BOOTLOADER_SIZE=20480
          CONFIG_LPC176X_USB_SERIAL_CFG=y
          CONFIG_LPC176X_USB_DFU_CFG=y
          CONFIG_USB_VENDOR_ID=0x1d50
          CONFIG_USB_PRODUCT_ID=0x614e
          CONFIG_SERIAL=
          CONFIG_FLASH_BOOT_OFFSET=
          CONFIG_INLINE_STEPPER_HACK=y
          CONFIG_HAVE_STEPPER_OPTIMIZED_BOTH_EDGE=y
          CONFIG_WANT_STEPPER_OPTIMIZED_BOTH_EDGE=y
          CONFIG_INITIAL_PINS=""
          CONFIG_HAVE_GPIO=y
          CONFIG_HAVE_GPIO_ADC=y
          CONFIG_HAVE_GPIO_SPI=y
          CONFIG_HAVE_GPIO_I2C=y
          CONFIG_HAVE_GPIO_HARD_PWM=y
          CONFIG_HAVE_STRICT_TIMING=y
          CONFIG_HAVE_CHIPID=y
          CONFIG_HAVE_BOOTLOADER_REQUEST=y
          EOF
          
          # Derleme öncesi temizlik ve derleme
          make olddefconfig
          make clean
          make

      - name: Convert klipper.bin to Robin_e3.bin
        run: |
          cd klipper
          ./scripts/update_mks_robin.py out/klipper.bin out/Robin_e3.bin

      - name: Upload Firmware to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Robin_e3-firmware
          path: klipper/out/Robin_e3.bin
