name: MKS Robin E3D Firmware Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Build Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git build-essential gcc-arm-none-eabi

      - name: Configure and Build Klipper Firmware
        run: |
          git clone https://github.com/Klipper3d/klipper.git --depth=1
          cd klipper
          
          # MKS Robin E3D v1.1 için Klipper make menuconfig ayarları
          cat > .config << EOF
          CONFIG_MCU="stm32f103xe"
          CONFIG_STM32_FLASH_START_OFFSET=0x5000
          CONFIG_SERIAL_PORT_USB=y
          EOF
          
          # Derleme
          make olddefconfig
          make
          mv out/klipper.bin out/Robin_e3.bin

      - name: Upload Firmware to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Robin_e3-firmware
          path: klipper/out/Robin_e3.bin
