name: MKS Robin E3D Firmware Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Build Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git build-essential gcc-arm-none-eabi libnewlib-arm-none-eabi python3-dev

      - name: Configure and Build Klipper Firmware
        run: |
          # "--recursive" komutu, tüm alt depoları (submodule'ları) otomatik olarak klonlar.
          git clone --recursive https://github.com/Klipper3d/klipper.git
          cd klipper
          
          # Mevcut .config dosyasını silerek temiz bir başlangıç yapın.
          rm -f .config
          
          # MKS Robin E3D için hazır konfigürasyon dosyasını kullanın ve ardından derleyin
          cp config/generic-mks-robin-e3-usb-flashing.cfg .config
          
          # Derleme konfigürasyonunu oluşturmak için Klipper'ın dahili aracını kullanın.
          make olddefconfig
          
          # Derleme
          make
          
          # Oluşturulan dosyanın boyutunu kontrol edin. Bu, logda görünür olacaktır.
          ls -lh out/klipper.bin
          
          mv out/klipper.bin out/Robin_e3.bin

      - name: Upload Firmware to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Robin_e3-firmware
          path: klipper/out/Robin_e3.bin
