name: MKS Robin E3D Firmware Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Build Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git build-essential gcc-arm-none-eabi

      - name: Configure and Build Klipper Firmware
        run: |
          git clone https://github.com/Klipper3d/klipper.git --depth=1
          cd klipper
          
          # Varsayılan konfigürasyonu oluştur
          make olddefconfig
          
          # Doğru işlemciyi ve flaş ofsetini doğrudan dosyaya yazarak hata olasılığını ortadan kaldır
          sed -i 's/^# CONFIG_MCU is not set/CONFIG_MCU="stm32f103xe"/' .config
          sed -i 's/^# CONFIG_STM32_FLASH_START_OFFSET is not set/CONFIG_STM32_FLASH_START_OFFSET=0x5000/' .config
          sed -i 's/^# CONFIG_SERIAL_PORT_USB is not set/CONFIG_SERIAL_PORT_USB=y/' .config
          
          # Derleme
          make
          mv out/klipper.bin out/Robin_e3.bin

      - name: Upload Firmware to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Robin_e3-firmware
          path: klipper/out/Robin_e3.bin
