name: MKS Robin E3D Firmware Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Build Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git build-essential gcc-arm-none-eabi
          
      - name: Configure and Build Klipper Firmware
        run: |
          git clone https://github.com/Klipper3d/klipper.git --depth=1
          cd klipper
          
          # MKS Robin E3D v1.1 için Klipper make menuconfig ayarları
          # Doğru işlemci (STM32F103) ve bootloader ayarları
          cat > .config << EOF
          CONFIG_LOW_LEVEL_OPTIONS=y
          CONFIG_MACH_STM32=y
          CONFIG_BOARD_DIRECTORY="stm32"
          CONFIG_MCU="stm32f103xe"
          CONFIG_STM32_FLASH_START_OFFSET=0x5000
          CONFIG_USB_VENDOR_ID=0x1d50
          CONFIG_USB_PRODUCT_ID=0x614e
          CONFIG_SERIAL_PORT_USB=y
          CONFIG_INLINE_STEPPER_HACK=y
          CONFIG_HAVE_STEPPER_OPTIMIZED_BOTH_EDGE=y
          CONFIG_WANT_STEPPER_OPTIMIZED_BOTH_EDGE=y
          CONFIG_INITIAL_PINS=""
          CONFIG_HAVE_GPIO=y
          CONFIG_HAVE_GPIO_ADC=y
          CONFIG_HAVE_GPIO_SPI=y
          CONFIG_HAVE_GPIO_I2C=y
          CONFIG_HAVE_GPIO_HARD_PWM=y
          CONFIG_HAVE_STRICT_TIMING=y
          CONFIG_HAVE_CHIPID=y
          CONFIG_HAVE_BOOTLOADER_REQUEST=y
          EOF
          
          # Derleme
          make olddefconfig
          make

      - name: Convert klipper.bin to Robin_e3.bin
        run: |
          cd klipper
          ./scripts/update_mks_robin.py out/klipper.bin out/Robin_e3.bin

      - name: Upload Firmware to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Robin_e3-firmware
          path: klipper/out/Robin_e3.bin
